# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47a2f030dfa007447852cb8729eb24e2c7c35a53cbb196459308342db663ca66ed0c429bdd22e6eadf10ed03373f4c7f9fb1723cf6e02f128b784281ef09e42

test:
  secret_key_base: 0806c0397766f677577d7ea4841ae3c7074724d43a27e88651bee28e594bd2d6d7ce10cd913833e44b20db4259dabaac7185278bf71ac9dc2ac23ee52cd759ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
